import { useEffect, useRef, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Mail, Search, CalendarDays, Users, Grid2X2, SlidersHorizontal, ChevronDown, Inbox, File, Send, Archive, PanelRightClose, ScanLine, Check, ShieldCheck, Link2, Building2, RotateCcw, X, Clock3, MoreHorizontal, Pencil, CheckCircle2, ExternalLink, Info, AlertCircle } from "lucide-react";
import { seedState, active, missing, fullName, propName, premName, initialLetters, formatDate, sourceFor, approve, advanceClock, DAY, type Candidate } from "./lib/review";
import { INBOX, PREMISES, PROPERTIES, RELATIONSHIP_TYPES, type RelationshipType } from "./lib/mock-data";
type Tab = "ready" | "needs" | "done";
type Source = ReturnType<typeof sourceFor>;
function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description:string;children:React.ReactNode}) {
 return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal-content"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description><Dialog.Close className="modal-close icon-button" aria-label="Close dialog"><X/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export default function App() {
 const [state,setState]=useState(seedState), [panel,setPanel]=useState(false), [host,setHost]=useState<"outlook"|"dynamics">("outlook"), [tab,setTab]=useState<Tab>("ready");
 const [excluded,setExcluded]=useState<string[]>([]), [editId,setEditId]=useState<string|null>(null), [evidenceId,setEvidenceId]=useState<string|null>(null);
 const [selectedMessage,setSelectedMessage]=useState("digest"), [source,setSource]=useState<Source|null>(null), [recordId,setRecordId]=useState<string|null>(null), [query,setQuery]=useState("");
 const [controls,setControls]=useState(false), [failOne,setFailOne]=useState(false), [notice,setNotice]=useState(""), [undo,setUndo]=useState<Candidate|null>(null), [clockMessage,setClockMessage]=useState("");
 const latest=useRef(state);latest.current=state;
 const pending=state.candidates.filter(c=>active(c,state.now)), ready=pending.filter(c=>!missing(c).length), needs=pending.filter(c=>missing(c).length), selected=ready.filter(c=>!excluded.includes(c.id));
 const shown=tab==="ready"?ready:needs, completed=state.candidates.filter(c=>c.status==="added"), deferred=state.candidates.filter(c=>c.status==="later"&&!active(c,state.now)), dismissed=state.candidates.filter(c=>c.status==="dismissed");
 const record=state.contacts.find(c=>c.id===recordId), email=INBOX.find(m=>m.id===selectedMessage);
 const messages=INBOX.filter(m=>[m.senderName,m.senderEmail,m.subject].join(" ").toLowerCase().includes(query.toLowerCase()));
 const contacts=state.contacts.filter(c=>[fullName(c),c.email,...c.relationships.map(r=>r.property+" "+r.premises)].join(" ").toLowerCase().includes(query.toLowerCase()));
 const openReview=()=>{setPanel(true);setTab(ready.length?"ready":needs.length?"needs":"done");};
 const switchHost=(h:"outlook"|"dynamics")=>{setHost(h);setQuery("");setRecordId(null);};
 const reset=()=>{setState(seedState());setExcluded([]);setEditId(null);setEvidenceId(null);setPanel(false);setHost("outlook");setTab("ready");setNotice("");setUndo(null);setQuery("");setSelectedMessage("digest");setRecordId(null);setFailOne(false);setClockMessage("");setControls(false);};
 const update=(id:string,patch:Partial<Candidate>)=>setState(s=>({...s,candidates:s.candidates.map(c=>c.id===id?{...c,...patch,...(patch.propertyId!==undefined&&patch.propertyId!==c.propertyId?{premisesId:""}:{}),error:undefined}:c)}));
 const addSelected=()=>{
  const result=approve(state,selected.map(c=>c.id),failOne);setState(result.state);setFailOne(false);setUndo(null);
  const parts=[result.added?result.added+" new contact"+(result.added===1?"":"s")+" added":"",result.linked?result.linked+" premises relationship"+(result.linked===1?"":"s")+" linked":""].filter(Boolean);
  setNotice([parts.join(" and ")+(parts.length?" in Dynamics.":""),result.failed?"1 suggestion needs a retry.":""].filter(Boolean).join(" "));
  const rest=result.state.candidates.filter(c=>active(c,result.state.now));if(!rest.some(c=>!missing(c).length))setTab(rest.length?"needs":"done");
 };
 const dismiss=(c:Candidate,reason:string)=>{
  setUndo({...c});update(c.id,reason==="Review later"?{status:"later",deferredUntil:Math.max(state.lastNotice+7*DAY,state.now+DAY),reason}:{status:"dismissed",reason});
  setNotice(reason==="Review later"?fullName(c)+" deferred to a future weekly review.":fullName(c)+" removed: "+reason.toLowerCase()+".");
 };
 const viewRecord=(id:string)=>{switchHost("dynamics");setRecordId(id);};
 const advance=(days:number)=>{const result=advanceClock(state,days);setState(result.state);setClockMessage(result.message);};
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:"read_contact_review",description:"Read the simulated contact review. Does not change records.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){
   if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object.");
   const s=latest.current;return {simulation:true,pending:s.candidates.filter(c=>active(c,s.now)).map(c=>({id:c.id,name:fullName(c),kind:c.kind,missing:missing(c)})),added:s.activity.length,nextReminder:formatDate(s.lastNotice+7*DAY)};
  }},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 return <div className="app">
 <div className="prototype-bar"><div><span className="version">V2</span><strong>Embedded review</strong><span className="prototype-note">Interactive demo · simulated data</span></div><div className="host-switch" aria-label="Preview application"><button aria-pressed={host==="outlook"} className={host==="outlook"?"active":""} onClick={()=>switchHost("outlook")}><Mail/>Outlook</button><button aria-pressed={host==="dynamics"} className={host==="dynamics"?"active":""} onClick={()=>switchHost("dynamics")}><Grid2X2/>Dynamics</button></div><button className="quiet small" onClick={()=>setControls(true)} title="Demo controls"><SlidersHorizontal/>Demo controls</button></div>
 <header className="ms-header"><Grid2X2/><strong>{host==="outlook"?"Outlook":"Dynamics 365"}</strong><span className="app-divider"/><span className="header-context">{host==="outlook"?"Mail":"Property management"}</span><label className="global-search"><Search/><input aria-label={host==="outlook"?"Search inbox":"Search contacts"} placeholder={host==="outlook"?"Search your inbox":"Search contacts"} value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="avatar me">AM</span></header>
 <div className="ribbon"><div className="ribbon-label">{host==="outlook"?"Home":"Contacts"}</div><span className="ribbon-separator"/><span className="subtle">Alex Morgan</span><button className={"capture-trigger "+(panel?"selected":"")} onClick={()=>panel?setPanel(false):openReview()} aria-expanded={panel}><ScanLine/>Contact Capture<span className="count">{pending.length}</span></button></div>
 <div className={"workspace "+(panel?"with-panel":"")+(host==="dynamics"?" dynamics-workspace":"")}>
 <nav className="app-rail" aria-label="Applications"><button onClick={()=>switchHost("outlook")} className={host==="outlook"?"rail-active":""} aria-label="Outlook mail"><Mail/></button><button onClick={()=>switchHost("dynamics")} className={host==="dynamics"?"rail-active":""} aria-label="Dynamics contacts"><Users/></button><span><CalendarDays/></span></nav>
 <aside className="folder-nav">{host==="outlook"?<><p>Favourites <ChevronDown/></p><button onClick={()=>{setQuery("");setSelectedMessage("digest");}} className="folder active"><Inbox/>Inbox <span>{INBOX.length+state.notices.length}</span></button><div className="folder"><File/>Drafts</div><div className="folder"><Send/>Sent Items</div><div className="folder"><Archive/>Archive</div></>:<><p>Property management</p><button className="folder active" onClick={()=>setRecordId(null)}><Users/>Contacts</button><button className="folder" onClick={openReview}><ScanLine/>Contact review <span>{pending.length}</span></button><div className="folder"><Building2/>Properties</div></>}<p className="folder-heading">Your portfolio</p><div className="folder"><Building2/>Oak House</div><div className="folder"><Building2/>Riverside Court</div><div className="folder"><Building2/>Maple Gardens</div></aside>
 {host==="outlook"?<>
 <section className="message-list" aria-label="Inbox messages"><div className="list-heading"><h1>Inbox</h1><span>Focused</span></div><p className="date-separator">This week</p>{(!query||"contact capture weekly review".includes(query.toLowerCase()))&&<button onClick={()=>setSelectedMessage("digest")} className={"message-preview "+(selectedMessage==="digest"?"digest-preview":"")}><span className="avatar capture-avatar"><ScanLine/></span><div><div className="message-from">Contact Capture <time>09:00</time></div><strong>Your weekly contact review</strong><p>{pending.length?pending.length+" suggestions from your inbox":"You're all caught up"}</p><span className="mini-tag">Weekly review · {formatDate(state.lastNotice)}</span></div></button>}{messages.map(m=><button onClick={()=>setSelectedMessage(m.id)} className={"message-preview "+(selectedMessage===m.id?"digest-preview":"")} key={m.id}><span className="avatar">{initialLetters(m.senderName)}</span><div><div className="message-from">{m.senderName}</div><strong>{m.subject}</strong><p>{m.body.replace(/\n/g," ")}</p>{completed.some(c=>c.sourceId===m.id)&&<span className="mini-tag success-tag">Added to Dynamics</span>}</div></button>)}{query&&!messages.length&&<p className="empty-small">No matching sample emails.</p>}</section>
 <main className="reading-pane">{selectedMessage==="digest"?<>
 <div className="email-subject"><h2>Your weekly contact review</h2><span className="subtle">{formatDate(state.lastNotice)}</span></div><div className="sender"><span className="avatar capture-avatar"><ScanLine/></span><div><strong>Contact Capture</strong><p>To: Alex Morgan</p></div><span className="sender-time">09:00</span></div>
 <article className="digest"><div className="digest-brand"><ScanLine/> CONTACT CAPTURE</div><span className="eyebrow">YOUR WEEKLY REVIEW</span><h2>{pending.length?<>A few new faces.<br/>All in one place.</>:<>You're all<br/>caught up.</>}</h2><p>{pending.length?"We've picked out potential customer contacts from your recent emails. Review them here, then add them straight to Dynamics.":"Everything in this review has been handled. You can get back to your inbox."}</p>{pending.length>0&&<div className="digest-stats"><div><strong>{ready.length}</strong><span>ready to add</span></div><div><strong>{needs.length}</strong><span>need your input</span></div></div>}<button className="primary review-cta" onClick={openReview}>{pending.length?"Review "+pending.length+" suggestions":"View review history"}</button><div className="digest-note"><ShieldCheck/><span>{pending.length?"Nothing is added until you approve it.":"Your approved changes are available in Dynamics."}</span></div><div className="digest-footer"><Clock3/><span>One weekly reminder. {pending.length?"Next check: "+formatDate(state.lastNotice+7*DAY)+".":"No reminder unless something needs reviewing."}</span></div></article><p className="email-footnote">Prepared for Alex Morgan · Oak House, Riverside Court & Maple Gardens</p>
 </>:email&&<><button className="text-button" onClick={()=>setSelectedMessage("digest")}>Back to weekly review</button><EmailReading email={email}/></>}</main>
 </>:<main className="crm-main"><div className="crm-breadcrumb">Property management <span>/</span> Contacts {record&&<><span>/</span>{fullName(record)}</>}</div>
 {record?<><button className="text-button" onClick={()=>setRecordId(null)}>Back to all contacts</button><div className="crm-title"><span className="avatar large">{initialLetters(fullName(record))}</span><div><h1>{fullName(record)}</h1><p>{record.email}</p></div><span className="saved-label"><Check/>Saved</span></div><div className="record-tabs">Summary</div><div className="record-grid"><section className="crm-card"><h3>Contact information</h3><dl><dt>First name</dt><dd>{record.firstName}</dd><dt>Last name</dt><dd>{record.lastName}</dd><dt>Email address</dt><dd>{record.email}</dd><dt>Contact type</dt><dd>{record.type}</dd><dt>Contact ID</dt><dd>{record.id}</dd></dl></section><section className="crm-card"><h3>Active premises <span className="mini-tag">{record.relationships.length}</span></h3>{record.relationships.map((r,i)=><div className="premises-record" key={i}><Building2/><div><strong>{r.premises}, {r.property}</strong><p>{r.type}</p></div><span className="success-label">Active</span></div>)}{!record.relationships.length&&<p className="subtle">No premises relationships.</p>}</section><section className="crm-card timeline"><h3>Timeline</h3>{state.activity.filter(a=>a.contactId===record.id).map(a=><div key={a.id}><span className="timeline-dot"/><strong>{a.action} by Contact Capture</strong><p>Reviewed by Alex Morgan · {formatDate(state.now)}</p><button className="text-button" onClick={()=>setSource(sourceFor(state.candidates.find(c=>c.id===a.id)!))}>View source email</button></div>)}{!state.activity.some(a=>a.contactId===record.id)&&<p className="subtle">Existing Dynamics contact.</p>}</section></div></>:
 <><div className="crm-title"><div><h1>Active contacts</h1><p>Your customer contacts and their premises relationships.</p></div><span className="saved-label"><Check/>Up to date</span></div><div className="crm-review-banner"><div className="capture-logo"><ScanLine/></div><div><strong>{pending.length?pending.length+" suggestions ready for your review":"Contact review complete"}</strong><p>{pending.length?"The same review as Outlook. Pick up where you left off.":"Approved contacts and premises are already in this list."}</p></div><button className="secondary" onClick={openReview}>{pending.length?"Review contacts":"View history"}</button></div>
 <section className="crm-card contact-list"><div className="crm-list-heading"><h3>Contacts <span className="mini-tag">{contacts.length}</span></h3><span className="subtle">All contacts</span></div><div className="table-scroll"><table><thead><tr><th>Name</th><th>Email address</th><th>Premises</th><th>Type</th></tr></thead><tbody>{contacts.map(c=><tr key={c.id}><td><button className="contact-name" onClick={()=>setRecordId(c.id)}><span className="avatar">{initialLetters(fullName(c))}</span><span>{fullName(c)}{(c.new||c.updated)&&<small>{c.new?"Added by Contact Capture":"Premises updated"}</small>}</span></button></td><td>{c.email}</td><td>{c.relationships.map((r,i)=><div key={i}>{r.premises}, {r.property}<small>{r.type}</small></div>)}{!c.relationships.length&&"—"}</td><td>{c.type}</td></tr>)}</tbody></table></div>{!contacts.length&&<p className="empty-small">No contacts match this search.</p>}</section></>}</main>}
 {panel&&<aside className="review-panel" aria-label="Contact review"><div className="panel-heading"><span className="capture-logo"><ScanLine/></span><div><h2>Contact Capture</h2><p>Same review in Outlook & Dynamics</p></div><button className="icon-button" onClick={()=>setPanel(false)} aria-label="Close review"><PanelRightClose/></button></div><div className="panel-intro"><h3>{pending.length?"Ready when you are":"Review complete"}</h3><p>{pending.length?"Check the details. We'll take care of Dynamics.":"Your inbox contacts are up to date."}</p></div>
 {notice&&<div className={"result-notice "+(notice.includes("retry")?"warning":"")} role="status"><CheckCircle2/><div>{notice}{undo&&<button className="text-button" onClick={()=>{update(undo.id,{...undo,status:"pending"});setUndo(null);setNotice("Suggestion restored.");}}>Undo</button>}</div><button className="icon-button" aria-label="Dismiss result" onClick={()=>setNotice("")}><X/></button></div>}
 <div className="review-tabs" aria-label="Review groups"><button className={tab==="ready"?"active":""} aria-pressed={tab==="ready"} onClick={()=>setTab("ready")}>Ready to add <b>{ready.length}</b></button><button className={tab==="needs"?"active":""} aria-pressed={tab==="needs"} onClick={()=>setTab("needs")}>Needs input <b>{needs.length}</b></button><button className={tab==="done"?"active":""} aria-pressed={tab==="done"} onClick={()=>setTab("done")}>History</button></div>
 <div className="cards">{tab!=="done"&&shown.map(c=><ContactCard key={c.id} candidate={c} included={!excluded.includes(c.id)} onToggle={()=>setExcluded(ids=>ids.includes(c.id)?ids.filter(id=>id!==c.id):[...ids,c.id])} editing={editId===c.id} onEdit={()=>setEditId(editId===c.id?null:c.id)} evidence={evidenceId===c.id} onEvidence={()=>setEvidenceId(evidenceId===c.id?null:c.id)} onUpdate={patch=>update(c.id,patch)} onSource={()=>setSource(sourceFor(c))} onDismiss={reason=>dismiss(c,reason)}/>)}
 {tab!=="done"&&!shown.length&&<div className="empty-review"><CheckCircle2/><h3>{tab==="ready"?"Nothing ready to add":"No missing details"}</h3><p>{tab==="ready"&&needs.length?"Resolve the missing details in Needs input.":"Everything in this group has been handled."}</p>{needs.length>0&&<button className="secondary" onClick={()=>setTab("needs")}>Review missing details</button>}</div>}
 {tab==="done"&&<><div className="history-intro"><h3>Review history</h3><p>Decisions stay with this demo session.</p></div>{state.activity.map(a=><div className="history-item" key={a.id}><CheckCircle2/><div><strong>{a.name}</strong><p>{a.action}</p><button className="text-button" onClick={()=>viewRecord(a.contactId)}>View in Dynamics <ExternalLink/></button></div></div>)}{deferred.map(c=><div className="history-item" key={c.id}><Clock3/><div><strong>{fullName(c)}</strong><p>Review later · returns {formatDate(c.deferredUntil!)}</p><button className="text-button" onClick={()=>{update(c.id,{status:"pending"});setTab(missing(c).length?"needs":"ready");}}>Review now</button></div></div>)}{dismissed.map(c=><div className="history-item" key={c.id}><Archive/><div><strong>{fullName(c)}</strong><p>{c.reason}</p><button className="text-button" onClick={()=>{update(c.id,{status:"pending"});setTab(missing(c).length?"needs":"ready");}}>Restore suggestion</button></div></div>)}{!state.activity.length&&!deferred.length&&!dismissed.length&&<div className="empty-review"><Clock3/><p>Your approvals and decisions will appear here.</p></div>}</>}
 </div><div className="panel-footer">{tab==="ready"&&ready.length>0?<><button className="primary full" disabled={!selected.length} onClick={addSelected}>{selected.some(c=>c.error)?"Retry":"Approve"} {selected.length} suggestion{selected.length===1?"":"s"}</button><p>{selected.filter(c=>c.kind==="contact").length} new contacts · {selected.filter(c=>c.kind==="relationship").length} new premises links</p></>:<button className="secondary full" onClick={()=>setPanel(false)}>Back to {host==="outlook"?"inbox":"contacts"}</button>}<p><ShieldCheck/>Only approved changes are added to Dynamics.</p></div></aside>}
 </div><footer className="demo-footer"><span>Demo only · no live Outlook or Dynamics connection</span><span>Changes stay in this session · reload to restart</span></footer>
 <Modal open={!!source} onClose={()=>setSource(null)} title={source?.subject??"Source email"} description="The email behind this suggestion.">{source&&<><div className="source-meta"><strong>{source.senderName}</strong><span>{source.senderEmail}</span><span>To: Alex Morgan</span></div><div className="email-body">{source.body}</div></>}</Modal>
 <Modal open={controls} onClose={()=>setControls(false)} title="Explore the demo" description="Try the weekly reminder and a failed save. These controls only affect this demo."><section className="demo-section"><h3>Weekly reminder</h3><p>Demo date: <strong>{formatDate(state.now)}</strong>. Last reminder: {formatDate(state.lastNotice)}.</p><p>Only one prompt per seven days across Outlook and Dynamics. No pending suggestions means no reminder.</p><div className="demo-buttons"><button className="secondary" onClick={()=>advance(1)}>Advance 1 day</button><button className="secondary" onClick={()=>advance(7)}>Advance 1 week</button><button className="text-button" onClick={()=>advance(0)}>Check reminder now</button></div>{clockMessage&&<div className="clock-result" role="status">{clockMessage}</div>}<details><summary>Reminder history ({state.notices.length})</summary>{state.notices.map((n,i)=><p key={i}>{formatDate(n.date)} · {n.count} suggestions</p>)}</details></section><section className="demo-section"><h3>Failure and retry</h3><label className="failure-toggle"><input type="checkbox" checked={failOne} onChange={e=>setFailOne(e.target.checked)}/>Fail one suggestion in the next approval</label><p>Successful suggestions are saved. The failed one keeps its edits and can be retried.</p></section><section className="demo-section"><h3>Start again</h3><p>Resets sample contacts, edits, approvals and reminder history in this version.</p><button className="secondary" onClick={reset}><RotateCcw/>Reset this demo</button></section><p className="demo-disclaimer">This prototype simulates the embedded panels and weekly schedule. It does not install an Outlook add-in, send emails, or change real Dynamics records.</p></Modal>
 </div>;
}
function ContactCard({candidate:c,included,onToggle,editing,onEdit,evidence,onEvidence,onUpdate,onSource,onDismiss}:{candidate:Candidate;included:boolean;onToggle:()=>void;editing:boolean;onEdit:()=>void;evidence:boolean;onEvidence:()=>void;onUpdate:(patch:Partial<Candidate>)=>void;onSource:()=>void;onDismiss:(reason:string)=>void}) {
 const fields=missing(c);
 return <div className={"contact-card "+(fields.length?"needs-detail ":"")+(c.error?"save-failed":"")}><div className="card-top"><span className="avatar">{initialLetters(fullName(c))}</span><div><h4>{fullName(c)||"Unnamed contact"}</h4><p>{c.email}</p></div>{!fields.length&&<input aria-label={"Include "+fullName(c)} type="checkbox" checked={included} onChange={onToggle}/>}<details className="card-menu"><summary aria-label={"Actions for "+fullName(c)}><MoreHorizontal/></summary><div>{["Review later","Not a customer","Already handled"].map(reason=><button key={reason} onClick={()=>onDismiss(reason)}>{reason}</button>)}</div></details></div>
 {c.kind==="relationship"&&<div className="relationship-tag"><Link2/>Existing contact · new premises</div>}
 {editing?<div className="edit-fields">{c.kind==="contact"&&<div className="field-pair"><label>First name<input value={c.firstName} onChange={e=>onUpdate({firstName:e.target.value})}/></label><label>Last name<input value={c.lastName} onChange={e=>onUpdate({lastName:e.target.value})}/></label></div>}<label>Property<select value={c.propertyId} onChange={e=>onUpdate({propertyId:e.target.value})}><option value="">Choose a property</option>{PROPERTIES.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="field-pair"><label>Premises<select value={c.premisesId} disabled={!c.propertyId} onChange={e=>onUpdate({premisesId:e.target.value})}><option value="">Choose premises</option>{PREMISES.filter(p=>p.propertyId===c.propertyId).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Relationship<select value={c.relationship} onChange={e=>onUpdate({relationship:e.target.value as RelationshipType})}><option value="">Choose relationship</option>{RELATIONSHIP_TYPES.map(r=><option key={r}>{r}</option>)}</select></label></div><div className="edit-note"><Check/>Edits kept in this session <button className="text-button" onClick={onEdit}>Done</button></div></div>:<div className="contact-details"><Building2/><span>{propName(c.propertyId)||"Choose a property"}{c.premisesId&&" · "+premName(c.premisesId)}<small>{c.relationship||"Relationship not specified"}</small></span></div>}
 {fields.length>0&&<div className="missing-details"><Info/><span>Check {fields.join(" and ")}.</span>{!editing&&<button className="text-button" onClick={onEdit}>Resolve</button>}</div>}
 {c.error&&<div className="save-error"><AlertCircle/>{c.error}</div>}
 {evidence&&<div className="evidence"><span>FROM THE EMAIL</span><blockquote>“{c.evidence}”</blockquote>{c.kind==="relationship"&&<p>Martin already has a contact record for Flat 2. This adds Flat 6 to the same record.</p>}<button className="text-button" onClick={onSource}><Mail/>Open source email</button></div>}
 <div className="card-actions"><button className="text-button" onClick={onEvidence} aria-expanded={evidence}>{evidence?"Hide evidence":"Why this suggestion?"}<ChevronDown/></button><button className="text-button" onClick={onEdit}><Pencil/>{editing?"Close editor":"Edit"}</button></div></div>;
}
function EmailReading({email}:{email:Source}) {
 return <><div className="email-subject"><h2>{email.subject}</h2></div><div className="sender"><span className="avatar">{initialLetters(email.senderName)}</span><div><strong>{email.senderName}</strong><p>{email.senderEmail}</p></div></div><div className="email-body">{email.body}</div></>;
}
